### ISSUE TITLE
can we use pip in pymol to install packages

### ISSUE THREAD

**Issue by autodataming** [evonove/pymol#1]
PyMOL >>> import pip
PyMOL>pip.main(['install','pprint'])
Traceback (most recent call last):
  File "C:\Program Files\PyMOL\PyMOL/modules\pymol\parser.py", line 419, in parse
    exec(layer.com2+"\n",self.pymol_names,self.pymol_names)
  File "<string>", line 1, in <module>
  File "C:\Program Files\PyMOL\PyMOL\py27\lib\site-packages\pip__init__.py", line 217, in main
    return command.main(cmd_args)
  File "C:\Program Files\PyMOL\PyMOL\py27\lib\site-packages\pip\basecommand.py", line 197, in main
    for name in ["pip._vendor", "distlib", "requests", "urllib3"]
  File "C:\Program Files\PyMOL\PyMOL\py27\lib\logging\config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Program Files\PyMOL\PyMOL\py27\lib\logging\config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'console': 'module' object has no attribute 'closed'

**Comment by hiteshpatel379** [comment]
PyMOL>help pip
 
DESCRIPTION
 
    Experimental and limited pip support for installing additional Python
    packages into PyMOL's bundled Python distribution. Type "pip help" for
    more information.
 
EXAMPLE
 
    pip install tkintertable
 
PyMOL>pip install numpy
Traceback (most recent call last):
  File "/home/hpatel/Tools/pymol/lib/python2.7/site-packages/pymol/externing.py", line 199, in pip
    main(["--disable-pip-version-check"] + shlex.split(command))
TypeError: 'module' object is not callable

**Comment by hiteshpatel379** [comment]
PyMOL>help conda
 
DESCRIPTION
 
    Experimental and limited conda wrapper for PyMOL bundles. Automatically
    passes "--yes" to "conda install".
 
EXAMPLE
 
    conda install biopython
 
PyMOL>conda install scipy

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
 conda finished with success

**Comment by ilkwonch** [comment]
>>> import pip
>>> pip.main(['install', 'packagename'])
https://stackoverflow.com/questions/26118613/how-to-install-python-package-inside-pymol
